-- Window Function
-- used to aggregate the data based upon window/partition in select


SELECT *, 
SUM(AMOUNT) OVER(PARTITION BY CUSTOMER_ID),
COUNT(*) OVER(PARTITION BY STAFF_ID),
COUNT(*) OVER(),
ROUND(AVG(AMOUNT) OVER(),2)
FROM PAYMENT;

-- Running Total using Window Function
SELECT 
*,
SUM(AMOUNT) OVER(PARTITION BY CUSTOMER_ID ORDER BY PAYMENT_DATE),
COUNT(*) OVER(PARTITION BY CUSTOMER_ID ORDER BY PAYMENT_DATE),
COUNT(*) OVER(PARTITION BY CUSTOMER_ID)
FROM PAYMENT
ORDER BY CUSTOMER_ID ASC;

-- RANK/DENSE RANK/FIRST VALUE/LEAD/LAG

SELECT
F.TITLE,
C.NAME,
F.LENGTH,
RANK() OVER(PARTITION BY C.NAME ORDER BY F.LENGTH),
DENSE_RANK() OVER(PARTITION BY C.NAME ORDER BY F.LENGTH),
FIRST_VALUE(F.LENGTH) OVER(PARTITION BY C.NAME ORDER BY F.LENGTH ASC), --FIRST VALUE SORTED IN THE GIVEN PARTITION 
FIRST_VALUE(F.LENGTH) OVER(PARTITION BY C.NAME ORDER BY F.LENGTH DESC),
LEAD(F.TITLE) OVER(PARTITION BY C.NAME ORDER BY F.TITLE ASC),
LAG(F.TITLE) OVER(PARTITION BY C.NAME ORDER BY F.TITLE ASC)
FROM FILM F
LEFT JOIN FILM_CATEGORY FC ON F.FILM_ID = FC.FILM_ID
LEFT JOIN CATEGORY C ON C.CATEGORY_ID = FC.CATEGORY_ID
ORDER BY C.NAME, 1;

-- WINDOW FUNCTIONS CANNOT BE USED IN WHERE CONDITION. WE CAN USE SUBQUERIES TO OVERCOME THAT ISSUE

SELECT * FROM(
SELECT
F.TITLE,
C.NAME,
F.LENGTH,
RANK() OVER(PARTITION BY C.NAME ORDER BY F.LENGTH),
DENSE_RANK() OVER(PARTITION BY C.NAME ORDER BY F.LENGTH DESC) AS DENSE
FROM FILM F
LEFT JOIN FILM_CATEGORY FC ON F.FILM_ID = FC.FILM_ID
LEFT JOIN CATEGORY C ON C.CATEGORY_ID = FC.CATEGORY_ID
ORDER BY NAME)
WHERE DENSE = 1;
